### ISSUE TITLE
NPC's die before you arrive

### ISSUE THREAD

**Issue by DerHobbs** [bythewood/esrp_quests#7] opened 2022-05-31 20:04 UTC
It often happens that the NPC's just die before you get there, you can just turn around and pick up your money ;)

**Comment by Hunter3001** [comment] 2022-06-01 01:19
I can confirm that, unfortunately it also happens to us.

**Comment by bythewood** [comment] 2022-06-01 01:35
Hrm, does it happen all the time or just randomly? I'm guessing they're probably being dropped to their deaths. 🤣

**Comment by bythewood** [comment] 2022-06-01 01:41
Actually, I'm wondering if they're killing each other, or being killed by other peds. 🤔

**Comment by DerHobbs** [comment] 2022-06-01 01:46
I had made a search on the prison island, there was no one there, so they either shot each other or they drowned while I was going to the island by boat :D

But yes, unfortunately they also like to fall down from slopes.

**Comment by bythewood** [comment] 2022-06-01 04:20
Changes committed. 😃 

I removed the auto Z increment from NPC spawning and instead am hoping that it will just keep trying until it spawns them correctly. Hopefully they were just falling to their deaths. XD Also added a global lock for each quest where only one player can take a quest at a time, to avoid masses of NPCs spawning. Hopefully this will help cut down on them murdering each other.

If this doesn't work, I'll look into ways to artificially make the NPCs immortal to everything but players. I just like the idea of perhaps a target getting eaten by a random bear and saving you the time.

**Comment by bythewood** [comment] 2022-06-01 04:22
Leaving this one open because I'm not sure I fixed it, or even identified the actual issue.

**Comment by DerHobbs** [comment] 2022-06-01 16:30
Unfortunately, the NPCs still die by themselves, you ride there suddenly 9 pieces die for no reason, and only one is left there.

**Comment by DerHobbs** [comment] 2022-06-01 16:46
https://prnt.sc/ONka8ijenuPi

For example, I accepted a mission where 12 npc spawn on the prison island, after that I sat down here, after a little more than 10 minutes everyone just died and I can collect my money.

**Closed** 2022-06-08 04:01 UTC
